# Generated by Django 5.1.4 on 2024-12-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='upassword',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
